# Data Import SQL

Converting all the empty strings in the csv file into NULL so that we can import it to the MySQL Workbench.

- From `.xlsx` to `.csv`: https://cloudconvert.com/xlsx-to-csv

In [1]:
import pandas as pd

## Converting Vaccination Dataset

In [19]:
df = pd.read_csv("CovidVaccEmpty.csv")
df = df.fillna("\\N")
df.to_csv("CovidVacc.csv", index=False)

In [23]:
df.to_csv("CovidVacc.csv", index=False)

## Converting Deaths Dataset

In [26]:
df = pd.read_csv("CovidDeathsEmpty.csv")
df = df.fillna("\\N")
df.to_csv("CovidDeaths.csv", index=False)

In [27]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2/24/2020,1.0,1.0,\N,\N,\N,\N,...,1803.987,\N,597.029,9.59,\N,\N,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2/25/2020,1.0,0.0,\N,\N,\N,\N,...,1803.987,\N,597.029,9.59,\N,\N,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2/26/2020,1.0,0.0,\N,\N,\N,\N,...,1803.987,\N,597.029,9.59,\N,\N,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2/27/2020,1.0,0.0,\N,\N,\N,\N,...,1803.987,\N,597.029,9.59,\N,\N,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2/28/2020,1.0,0.0,\N,\N,\N,\N,...,1803.987,\N,597.029,9.59,\N,\N,37.746,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85166,ZWE,Africa,Zimbabwe,4/26/2021,38102.0,16.0,34.714,1560.0,3.0,1.0,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
85167,ZWE,Africa,Zimbabwe,4/27/2021,38164.0,62.0,41.286,1565.0,5.0,1.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
85168,ZWE,Africa,Zimbabwe,4/28/2021,38191.0,27.0,30.143,1565.0,0.0,1.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
85169,ZWE,Africa,Zimbabwe,4/29/2021,38235.0,44.0,31.0,1567.0,2.0,1.714,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
85170,ZWE,Africa,Zimbabwe,4/30/2021,38257.0,22.0,30.286,1567.0,0.0,1.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571